### ISSUE TITLE
Not displaying info for some songs

### ISSUE THREAD

**Issue by nmackowiakk** [L3-N0X/spicetify-dj-info#22]
![bild](https://github.com/user-attachments/assets/86884887-0cff-4423-b0ba-7cc5c4826fd9)
As shown in the screenshot, some songs are missing info. I don't know if this is related to the extension itself or to info provider.

**Comment by L3-N0X** [comment]
Sometimes there is really no info provided by spotify for the song, so I think this might be the case here. Sometimes it can also be due to poor internet connection and the lazy loading of spotify, so sometimes reopening the playlist will show information again. 
I'll may add a clear cache button in the settings at some point to make clear that the info gets shown once spotify adds the info to the song.

**Comment by nmackowiakk** [comment]
Everything works fine today. Must've been some temporary issue.
