### ISSUE TITLE
"DJ info" column is empty in playlists 

### ISSUE THREAD

**Issue by mehr-zarathustra** [L3-N0X/spicetify-dj-info#7]
Hi, first of all, thank you for this very useful extension. However, while the info is visible in the "now-playing" section on the left bottom, I don't see the info visible in the playlist. The column is visible, but empty (see screenshot). Could there be something in the experimental features I have to enable/disable?

Thanks 
<img width="1827" alt="SCR-20230805-nrpu" src="https://github.com/L3-N0X/spicetify-dj-info/assets/12400962/8bf82651-866e-4e33-9a42-7f29c7650b9d">

**Comment by L3-N0X** [comment]
I recently fixed this bug, at least i thought so. And for me the info is still displayed correctly.
Can you please run `spicetify upgrade` or `spicetify apply` to make sure you have the newest version of my extension. Or if you have installed it manually, make sure to replace the old Extension file with the newest one.
You can check if the newest version is used when you go in the menu at the profile picture and when there is a 'year' option in dj info settings, then you have the newest version already installed.

When you have the newest version, but still no info, could you please close spotify and open it again with this command `spicetify enable-devtools` and then press ctrl + shift + i to open the devtools, then go to the console and look for a red error which is caused by djinfo.js and make a screenshot.

**Comment by L3-N0X** [comment]
Spotify updated today on my PC and then I had the same issue. Extension is fixed and should now work again!
